added round number in statuspanel
TheDeadXGamer/SmurfTowerDefense pull request #124
Opened 2024-12-16 21:56 UTC by arvid-max

2024-12-16 23:54 UTC, erzet07 commented on src/main/java/com/group34/View/Shop/ShopModel.java
> +    public Game getGame() {
Kanske missar, men jag ser inte var denna används.

2024-12-16 23:56 UTC, erzet07 commented on src/main/java/com/group34/View/Shop/ShopController.java
> +    public Game getGame() {
Kanske missar, men jag ser inte var denna används.

2024-12-17 00:09 UTC, erzet07 requested changes
Osäker på implementationen av Observer du har gjort. Mer specifikt hur du subscribar.

2024-12-17 00:09 UTC, erzet07 commented on src/main/java/com/group34/View/StatusPanel.java
> +        // adding this as an observer to the status model (which in turn registers as an observer to a bunch of observables)
Tror inte detta är bra sätt att subscriba på. Man brukar göra så att det finns en Manager som ägs av någon specifik klass (i det här fallet statusModel). Det kanske är sådär viktigt här men så som jag fattar det brukar man fixa med subscriptions i applikationen. Så jag gjorde det var att låta managern vara singleton så vem som helst kunde få samma instans av den. Är generellt osäker men tror inte detta är super bra lösning.

2024-12-17 15:42 UTC, arvid-max commented on src/main/java/com/group34/View/StatusPanel.java
> +        // adding this as an observer to the status model (which in turn registers as an observer to a bunch of observables)
Det kanske skulle vara en bättre implementation om det var en observable med en/flera observers, men här är det tvärt om. Om man ska göra subscriptions i applikationen här så måste man skapa instanser av observers och observables direkt i applikationen, och jag tycker inte det funkar här. Jag tycker detta är en effektiv implementation av observer pattern i detta sammanhanget, det är en ganska vanlig implementation också.

2024-12-19 11:51 UTC, merged