19 skapa waypoints
TheDeadXGamer/SmurfTowerDefense pull request #47
Opened 2024-11-27 18:39 UTC by Weevild

Implemented a waypoint system using queues and Point2D coordinates. Also made a tool for finding coordinates on a map by clicking with the cursor and then printing out and storing the waypoints in a txt file.

2024-11-27 20:23 UTC, Weevild commented
Hade väldigt stora problem med att merge:a pga Enemy Draft förändringarna så kolla gärna så att inte era förändringar/tillägg försvann/ändrades

2024-11-29 10:47 UTC, TheDeadXGamer commented on pom.xml
Line 13: Vi använder inte JavaFX i projektet så den borde inte vara med.

2024-11-29 10:54 UTC, TheDeadXGamer requested changes
Ser mestadels bra ut! Har lagt några kommentarer på saker som jag tyckte va lite udda. Men annars stabilt!

2024-11-29 10:54 UTC, TheDeadXGamer commented on .vscode/settings.json
Den här borde ha ignorerats av .gitignore, kolla så du har den ignorerad i den filen.

2024-11-29 10:54 UTC, TheDeadXGamer commented on src/main/java/com/group34/Model/Enemy/EnemyPath.java
> +        addWaypoint(0.0, 0.4);    // Start at left, 40% down
Det känns som vi borde göra så att den tar emot en lista av Tuples så att vi kan initialisera för andra banor också. I nuläget funkar den bara för BaseMap.

2024-11-29 10:54 UTC, TheDeadXGamer commented on src/main/java/com/group34/Model/Enemy/WaypointPanel.java
> +            InputStream imageStream = getClass().getResourceAsStream("/assets/Maps/BaseMap.png");
Vår GameView slänger redan upp bakgrundsbilden. Jag tror inte vi bör göra det igen.

2024-11-29 12:16 UTC, Weevild commented on pom.xml
AH, det måste ha varit en kvarleva, tog bort den

2024-11-29 12:19 UTC, Weevild commented on src/main/java/com/group34/Model/Enemy/EnemyPath.java
> +        addWaypoint(0.0, 0.4);    // Start at left, 40% down
Aa yes det är tänkt att göras härnäst. Waypointsen som initialiseras är inte riktiga waypoints. Jag har en application som printar ut Point2D koordinater i en txt fil och konsolen som man kanske kan dra nytta av sen för olika mappar t.ex.

2024-11-29 12:23 UTC, Weevild commented on src/main/java/com/group34/Model/Enemy/WaypointPanel.java
> +            InputStream imageStream = getClass().getResourceAsStream("/assets/Maps/BaseMap.png");
Är du säker? Denna applikation är separat från GameView och används bara för att kunna mappa koordinater så tror inte den kan nå GameView i Game mappen.

2024-11-29 17:37 UTC, TheDeadXGamer approved these changes
Ser bra ut!

2024-11-29 17:38 UTC, merged