58 implement abstract factory pattern for towers
TheDeadXGamer/SmurfTowerDefense pull request #63
Opened 2024-12-03 13:12 UTC by TheDeadXGamer

@erzet07 Har ändrat så att LightningBoltFactory nu är abstract och även enkapsulerar ThunderSmurf, då den är en uppgradering av LightningSmurf.

2024-12-03 15:27 UTC, Weevild commented
Jag kanske är blind men du pratar om att du har ändrat LightningBoltFactory till att vara abstract men jag hittar ingen sådan fil här. Din första commit leder mig till LightningSmurfFactory och den har ingen abstract factory implementation. 

Annars asbra med JavaDoc kommentarerna och clean-up:en!

2024-12-03 15:30 UTC, Weevild requested changes

2024-12-03 15:30 UTC, Weevild commented on src/main/java/com/group34/Model/Tower/LightningSmurfFactory.java
> +            default:
Är kanske en abstract factory implementation lämplig här också? I och med att vi skalar upp och fler och fler torn läggs till blir detta jobbigt att underhålla och bryter nog mot Open-Closed principle.

2024-12-03 15:30 UTC, Weevild commented on src/main/java/com/group34/Model/Tower/TowerFactory.java
> +    abstract public Tower createTower(String type, Point2D position);
Se kommentaren för LightningSmurfFactory

2024-12-03 20:37 UTC, erzet07 approved these changes

2024-12-04 10:32 UTC, TheDeadXGamer commented on src/main/java/com/group34/Model/Tower/LightningSmurfFactory.java
> +            default:
Japp, insåg att jag hade misstolkat den helt och hållet. Fixat i nya pushen.

2024-12-04 10:35 UTC, TheDeadXGamer commented
Har ändrat så att den faktiskt e abstrakt nu. Har även satt konkreta tal på damage, attackSpeed och range i både ThunderSmurf och LightningSmurf då jag kände att det inte va något man skulle få göra direkt i konstruktorn.

2024-12-04 11:17 UTC, Weevild commented on src/main/java/com/group34/Model/Tower/LightningSmurfFactory.java
> +            default:
Ser bra ut!

2024-12-04 11:18 UTC, Weevild approved these changes
Fixes have been imlpemented

2024-12-04 11:50 UTC, merged